import sys
import os
from datetime import datetime

# Allow running from project root: python orchestrator.py
sys.path.insert(0, os.path.dirname(__file__))

import markdown as md
from agents.ai_agent import run as get_ai_news
from email_sender import send_briefing


# ---------------------------------------------------------------------------
# HTML email template
# ---------------------------------------------------------------------------

def _ai_section_html(content_html: str) -> str:
    return f"""
    <table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:32px;">
      <tr>
        <td style="border-left:4px solid #6366f1; padding-left:16px;">
          <p style="margin:0 0 10px 0; font-size:11px; font-weight:700; letter-spacing:2px;
                     text-transform:uppercase; color:#6366f1;">AI &amp; Machine Learning</p>
          <div style="font-size:15px; line-height:1.75; color:#1e293b;">
            {content_html}
          </div>
        </td>
      </tr>
    </table>
    """


def build_html_email(ai_news_md: str, date_str: str) -> str:
    # Convert markdown output from Groq to HTML
    ai_news_html = md.markdown(ai_news_md, extensions=["nl2br"])

    # Strip the outer <h2> that duplicates the section header (Groq adds "## AI News — date")
    # We keep it since it acts as a title inside the section
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Morning Briefing</title>
</head>
<body style="margin:0; padding:0; background-color:#f1f5f9; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">

  <!-- Outer wrapper -->
  <table width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#f1f5f9">
    <tr>
      <td align="center" style="padding:32px 16px;">

        <!-- Card -->
        <table width="620" cellpadding="0" cellspacing="0" border="0"
               style="max-width:620px; background:#ffffff; border-radius:12px;
                      box-shadow:0 4px 24px rgba(0,0,0,0.08); overflow:hidden;">

          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#0f172a 0%,#1e3a5f 100%);
                        padding:36px 40px 28px 40px;">
              <p style="margin:0 0 6px 0; font-size:12px; font-weight:600; letter-spacing:3px;
                         text-transform:uppercase; color:#94a3b8;">Your Daily Digest</p>
              <h1 style="margin:0; font-size:28px; font-weight:800; color:#f8fafc;
                          letter-spacing:-0.5px;">Morning Briefing</h1>
              <p style="margin:10px 0 0 0; font-size:15px; color:#94a3b8;">{date_str}</p>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding:36px 40px 8px 40px;">
              {_ai_section_html(ai_news_html)}
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background:#f8fafc; padding:20px 40px; border-top:1px solid #e2e8f0;">
              <p style="margin:0; font-size:12px; color:#94a3b8; text-align:center;">
                Generated by your Morning Briefing Agent &nbsp;·&nbsp; {date_str}
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>

</body>
</html>"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    today = datetime.now()
    date_str = today.strftime("%A, %B %d, %Y")
    subject = f"Morning Briefing — {date_str}"

    print("[orchestrator] Running AI News Agent...")
    ai_news_md = get_ai_news()

    print("[orchestrator] Building HTML email...")
    html = build_html_email(ai_news_md, date_str)

    print("[orchestrator] Sending email...")
    send_briefing(subject, html)

    print("[orchestrator] All done!")


if __name__ == "__main__":
    main()
